name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - full-deploy-experiment

jobs:
  Upload_Data_Folder:
    runs-on: ubuntu-latest
    steps:
      - name: Create repo target
        run: mkdir -p gittarget
      - name: Download Repo
        uses: actions/checkout@v2
        with:
          path: 'gittarget'
      - name: List Contents Now
        run: ls -gRC
      - name: Promote the data folder
        run: mkdir -p path/to/artifact/data
        run: mv -v gittarget/data path/to/artifact/data
      - name: Remove files we don't need
        run: rm -rv gittarget
      - name: List Content to Upload
        run: ls -gRC
