name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - full-deploy-experiment

jobs:
  Upload_Data_Folder:
    runs-on: ubuntu-latest
    steps:
        # Checkout the repo
      - name: Create Artifact Folder
        run: mkdir -p path/to/artifact
      - name: Download Repo to Artifact Folder
        uses: actions/checkout@v2
        with:
          path: 'path/to/artifact'
      - name: List all
        run: ls -gRC
