name: Upload changed files To Azure Blob Storage
on:
  push:
    branches: # only main branch with updates to data/** contents
      - main
    paths:
      - 'data/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Covid_Static_Data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v2
      - name: Create the artifact folder
        run: mkdir -p path/to/artifact
      - name: Promote the data folder
        run: mv -v data path/to/artifact
      - name: List Content to Upload
        run: ls -gRC path/to/artifact
      - uses: StateOfCalifornia/azblob-upload-artifact@master     
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: '$web'
          name: .
          path: path/to/artifact
          cleanup: false
          sync: false   