name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
      - uses: actions/checkout@v2
      - run: ls -R 
