name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - full-deploy-experiment

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
        # Checkout the repo
      - uses: actions/checkout@v2
        with:
          path: '/path/to/artifact/data'
      - run: mkdir -p path/to/artifact/data
      - name: List all
        run: ls -gRC
