name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - main

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      - name: thing
      - run: ls -R 
