name: Upload changed files To Azure Blob Storage
on:
  push:
    branches:
      - full-deploy-experiment

jobs:
  Upload_Data_Folder:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v2
      - name: Create the artifact folder
        run: mkdir -p path/to/artifact
      - name: Promote the data folder
        run: mv -v data path/to/artifact
      - name: List Content to Upload
        run: ls -gRC path/to/artifact
