name: Track data updates
on:
  push:
    branches:
      - main
      - CovidStateDashboardTables_Staging

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        run: echo ${GITHUB_REF_NAME}
