name: Track equity data updates
on:
  push:
    branches:
      - main
    paths:
      - 'data/reviewed/equitydash/equitytopboxdatav2.json'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "UTC"

      - uses: actions/checkout@v2
      - run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run updateEquityStatus
          git add status/last_equity_update.json
          git commit -m "updated last equity status"
          git push origin main

