name: Track data updates
on:
  push:
    branches:
      - main
    paths:
      - 'data/dashboard/confirmed-cases/california.json'
      - 'data/daily-stats-v2.json'
      - 'data/reviewed/equitydash/equitytopboxdatav2.json'
      - 'data/dashboard/vaccines/sparkline.json'
      - 'data/dashboard/confirmed-deaths/california.json'
      - 'data/dashboard/positivity-rate/california.json'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "UTC"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Verify Changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0

      # - name: debugging
      #   run: |
      #     echo "FILES CHANGED"
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done

      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true

      - name: Update time stamp (cases)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/dashboard/confirmed-cases/california.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_cases_update.json
          git add data/status/last_cases_update.json
          git commit -m "updated last deaths status"

      - name: Update time stamp (dashboard)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/daily-stats-v2.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_dashbboard_update.json
          git add data/status/last_dashbboard_update.json
          git commit -m "updated last deaths status"

      - name: Update time stamp (equity)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/reviewed/equitydash/equitytopboxdatav2.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_equity_update.json
          git add data/status/last_equity_update.json
          git commit -m "updated last deaths status"

      - name: Update time stamp (vax)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/dashboard/vaccines/sparkline.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_vax_update.json
          git add data/status/last_vax_update.json
          git commit -m "updated last deaths status"

      - name: Update time stamp (deaths)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/dashboard/confirmed-deaths/california.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_deaths_update.json
          git add data/status/last_deaths_update.json
          git commit -m "updated last deaths status"

      - name: Update time stamp (posrate)
        if: contains(steps.changed-files.outputs.all_changed_files, 'data/dashboard/positivity-rate/california.json')
        run: |
          node src/logUpdateTime.js ./data/status/last_posrate_update.json
          git add data/status/last_posrate_update.json
          git commit -m "updated last posrate status"

      - name: update all changed timestamps to git
        run: |
          git pull
          git push origin main


      # Push built site files to S3 production bucket    
      - name: Deploy to S3 (data/status)
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'data.covid19.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: ./data/status
          DEST_DIR: data/status

      #
      # Invalidate Cloudfront production distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'EHNPIZWYYWA31'
          PATHS: '/data/status/* /data/status'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
