name: Upload To Amazon S3 / Clear Cloudfront cache
on:
  push:
    branches:
      - main
    paths:
      - 'data/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 180
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # Push built site files to S3 production bucket   
      - name: Deploy to S3 (data)
        run: aws s3 sync --delete ./data s3://data.covid19.ca.gov/data

      #
      # Invalidate Cloudfront production distribution (everything under data)
      # doc on invalidation paths: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects-paths
      - name: invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id EHNPIZWYYWA31 --paths "/data*"

